# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20180618_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recard',
            name='is_body',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], default=0, verbose_name='是否有人'),
        ),
        migrations.AlterField(
            model_name='recard',
            name='oneself',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], default=0, verbose_name='是否是本人'),
        ),
        migrations.AlterField(
            model_name='recard',
            name='turn',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], default=0, verbose_name='是否转头'),
        ),
        migrations.AlterField(
            model_name='recard',
            name='up_head',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], default=0, verbose_name='是否抬头'),
        ),
    ]
