# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180618_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorinfo',
            name='site_number',
            field=models.CharField(max_length=32, verbose_name='座位编号'),
        ),
        migrations.AlterField(
            model_name='recard',
            name='site_number',
            field=models.CharField(max_length=32, verbose_name='座位编号'),
        ),
    ]
