# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20180620_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorinfo',
            name='idCard',
            field=models.CharField(db_index=True, max_length=32, verbose_name='考生身份证'),
        ),
        migrations.AlterField(
            model_name='examinee',
            name='idCard',
            field=models.CharField(db_index=True, max_length=32, verbose_name='考生身份证号码'),
        ),
        migrations.AlterField(
            model_name='recard',
            name='idCard',
            field=models.CharField(db_index=True, max_length=32, verbose_name='考生身份证'),
        ),
    ]
