# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20180620_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinee',
            name='name',
            field=models.CharField(default='', max_length=32, verbose_name='考生姓名'),
        ),
    ]
