# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_examinee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recard',
            name='is_login',
            field=models.IntegerField(choices=[(1, '是'), (2, '否')], default=0, verbose_name='是否登录'),
        ),
    ]
