# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-24 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20180624_0954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recard',
            new_name='Record',
        ),
    ]
